package org.coolreader.crengine;

public class FontsPangramms {

	public static String[] RUSSIAN = {
			"Эй, цирюльникъ, ёжик выстриги, да щетину ряхи сбрей, феном вошь за печь гони!",
			"Экс-граф? Плюш изъят. Бьём чуждый цен хвощ!",
			"Эй, жлоб! Где туз? Прячь юных съёмщиц в шкаф.",
			"— Любя, съешь щипцы, — вздохнёт мэр, — кайф жгуч.",
			"В чащах юга жил-был цитрус? — да, но фальшивый экземпляръ!",
			"Южно-эфиопский грач увёл мышь за хобот на съезд ящериц.",
			"Аэрофотосъёмка ландшафта уже выявила земли богачей и процветающих крестьян.",
			"Шифровальщица попросту забыла ряд ключевых множителей и тэгов.",
			"Съешь ещё этих мягких французских булок, да выпей же чаю",
			"Щипцами брюки разлохмачу, Гребёнкой волосы взъерошу. Эффектно ожидать удачу,	До самой смерти я не брошу!",
			"Подъём с затонувшего эсминца легкобьющейся древнегреческой амфоры сопряжён с техническими трудностями.",
			"Завершён ежегодный съезд эрудированных школьников, мечтающих глубоко проникнуть в тайны физических явлений и химических реакций.",
			"Всё ускоряющаяся эволюция компьютерных технологий предъявила жёсткие требования к производителям как собственно вычислительной техники, так и периферийных устройств.",
			"Шалящий фавн прикинул объём горячих звезд этих вьюжных царств.",
			"Эх, жирафы честно в цель шагают, да щук объять за память ёлкой...",
			"Расчешись! Объявляю: туфли у камина, где этот хищный ёж цаплю задел.",
			"Лингвисты в ужасе: фиг выговоришь этюд: «подъём челябинский, запах щец».",
			"Съел бы ёж лимонный пьезокварц, где электрическая юла яшму с туфом похищает.",
			"Официально заявляю читающим: даёшь подъем операции Ы! Хуже с ёлкой бог экспериментирует.",
			"Эти ящерицы чешут вперёд за ключом, но багаж в сейфах, поди подъедь...",
			"Бегом марш! У месторождения кварцующихся фей без слёз хочется электрическую пыль.",
			"Хрюкнул ёж «Тыща», а ведь село Фершампенуаз — это центр Нагайбакского района Челябинской области.",
			"Эх, взъярюсь, толкну флегматика: «Дал бы щец жарчайших, Пётр!»",
			"Здесь фабула объять не может всех эмоций — шепелявый скороход в юбке тащит горячий мёд.",
			"Художник-эксперт с компьютером всего лишь яйца в объёмный низкий ящик чохом фасовал.",
			"Юный директор целиком сжевал весь объём продукции фундука (товара дефицитного и деликатесного), идя энергично через хрустящий камыш.",
			"Мюзикл-буфф «Огнедышащий простужается ночью» (в 12345 сценах и 67890 эпизодах).",
			"Обдав его удушающей пылью, множество ярких фаэтонов исчезло из цирка.",
			"Безмозглый широковещательный цифровой передатчик сужающихся экспонент.",
			"Однажды съев фейхоа, я, как зацикленный, ностальгирую всё чаще и больше по этому чуду.",
			"Вопрос футбольных энциклопедий замещая чушью: эй, где съеден ёж?",
			"Борец за идею Чучхэ выступил с гиком, шумом, жаром и фырканьем на съезде — и в ящик.",
			"Твёрдый, как ъ, но и мягкий, словно ь, юноша из Бухары ищет фемину-москвичку для просмотра цветного экрана жизни.",
			"Блеф разъедает ум, чаще цыгана живёшь беспокойно, юля — грех это!",
			"БУКВОПЕЧАТАЮЩЕЙ СВЯЗИ НУЖНЫ ХОРОШИЕ Э/МАГНИТНЫЕ РЕЛЕ. ДАТЬ ЦИФРЫ (1234567890+= .?-)",
			"Пиши: зять съел яйцо, ещё чан брюквы... эх! Ждем фигу!",
			"Флегматичная эта верблюдица жует у подъезда засыхающий горький шиповник.",
			"Вступив в бой с шипящими змеями — эфой и гадюкой, — маленький, цепкий, храбрый ёж съел их.",
			"Подъехал шофёр на рефрижераторе грузить яйца для обучающихся элитных медиков.",
			"Широкая электрификация южных губерний даст мощный толчок подъёму сельского хозяйства.",
			"Государев указ: душегубцев да шваль всякую высечь, да калёным железом по щекам этих физиономий съездить!"
	};

	public static String[] ENGLISH = {
			"Brick quiz whangs jumpy veldt fox!",
			"Quick wafting zephyrs vex bold Jim.",
			"Sphinx of black quartz judge my vow!",
			"The five boxing wizards jump quickly.",
			"Mr. Jock, TV quiz Ph.D., bags few lynx.",
			"Pack my box with five dozen liquor jugs.",
			"Jackdaws love my sphinx of black quartz.",
			"Sympathizing would fix Quaker objectives.",
			"Five big quacking zephyrs jolt my wax bed.",
			"The quick brown fox jumps over the lazy dog.",
			"Many-wived Jack laughs at probes of sex quiz.",
			"Mix Zapf with Veljovic and get quirky Beziers.",
			"Dumpy kibitzer jingles as exchequer overflows.",
			"Puzzled women bequeath jerks very exotic gifts.",
			"Brawny gods just flocked up to quiz and vex him.",
			"Viewing quizzical abstracts mixed up hefty jocks.",
			"Playing jazz vibe chords quickly excites my wife.",
			"Jim just quit and packed extra bags for Liz Owen.",
			"Five wine experts jokingly quizzed sample chablis.",
			"William Jex quickly caught five dozen Republicans.",
			"A large fawn jumped quickly over white zinc boxes.",
			"Cozy lummox gives smart squid who asks for job pen.",
			"Turgid saxophones blew over Mick's jazzy quiff.",
			"Big July earthquakes confound zany experimental vow.",
			"Exquisite farm wench gives body jolt to prize stinker.",
			"Six big devils from Japan quickly forgot how to waltz.",
			"The vixen jumped quickly on her foe barking with zeal.",
			"Five or six big jet planes zoomed quickly by the tower.",
			"Crazy Fredericka bought many very exquisite opal jewels.",
			"My grandfather picks up quartz and valuable onyx jewels.",
			"Six crazy kings vowed to abolish my quite pitiful jousts.",
			"Sixty zippers were quickly picked from the woven jute bag.",
			"The job of waxing linoleum frequently peeves chintzy kids.",
			"Jack amazed a few girls by dropping the antique onyx vase!",
			"How razorback-jumping frogs can level six piqued gymnasts!",
			"We have just quoted on nine dozen boxes of gray lamp wicks.",
			"May Jo equal the fine record by solving six puzzles a week?",
			"West quickly gave Bert handsome prizes for six juicy plums.",
			"Jay visited back home and gazed upon a brown fox and quail.",
			"Fred specialized in the job of making very quaint wax toys.",
			"Just keep examining every low bid quoted for zinc etchings.",
			"Freight to me sixty dozen quart jars and twelve black pans.",
			"Verily the dark ex-Jew quit Zionism, preferring the cabala.",
			"A quick movement of the enemy will jeopardize six gunboats.",
			"Jeb quickly drove a few extra miles on the glazed pavement.",
			"All questions asked by five watch experts amazed the judge.",
			"Grumpy wizards make toxic brew for the evil Queen and Jack.",
			"The exodus of jazzy pigeons is craved by squeamish walkers.",
			"We promptly judged antique ivory buckles for the next prize.",
			"Back in June we delivered oxygen equipment of the same size.",
			"Lazy movers quit hard-packing of papier-mâché jewelry boxes.",
			"While waxing parquet decks, Suez sailors vomit jauntily abaft.",
			"How vexing a fumble, to drop a jolly zucchini in the quicksand!",
			"Astronaut Quincy  B. Zack defies gravity with six jet fuel pumps.",
			"My help squeezed back in again and joined the weavers after six.",
			"New farm hand (picking just six quinces) proves strong but lazy.",
			"Alfredo just must bring very exciting news to the plaza quickly.",
			"Back in my quaint garden jaunty zinnias vie with flaunting phlox.",
			"Jaded zombies acted quaintly but kept driving their oxen forward.",
			"Hark! Toxic jungle water vipers quietly drop on zebras for meals!",
			"Six jabbering pacifist vultures were ambushed by the zany quagmire.",
			"Six big juicy steaks sizzled in a pan as five workmen left the quarry.",
			"Will Major Douglas be expected to take this true-false quiz very soon?",
			"The juke box music puzzled a gentle visitor from a quaint valley town.",
			"Just work for improved basic techniques to maximize your typing skill.",
			"A mad boxer shot a quick, gloved jab to the jaw of his dizzy opponent.",
			"Verbatim reports were quickly given by Jim Fox to his amazed audience.",
			"When we go back to Juarez, Mexico, do we fly over picturesque Arizona?",
			"Questions of a zealous nature have become by degrees petty waxen jokes.",
			"About sixty codfish eggs will make a quarter pound of very fizzy jelly.",
			"Murky haze enveloped a city as jarring quakes broke fourty-six windows.",
			"King Alexander was just partly overcome after quizzing Diogenes in his tub.",
			"The July sun caused a fragment of black pine wax to ooze on the velvet quilt.",
			"Two hardy boxing kangaroos jet from Sydney to Zanzibar on quicksilver pinions.",
			"Perhaps President Clinton's amazing sax skills will be judged quite favorably.",
			"Was there a quorum of able whizzkids gravely exciting the jaded fish at ATypI?",
			"Ebenezer unexpectedly bagged two tranquil aardvarks with his jiffy vacuum cleaner.",
			"Fabled reader with jaded, roving eye seized by quickened impulse to expand budget.",
			"For only ^$49, jolly housewives made “inexpensive” meals using quick-frozen vegetables.",
			"The sex life of the woodchuck is a provocative question for most vertebrate zoology majors.",
			"Breezily jangling ^$3,416,857,209 wise advertiser ambles to the bank, his exchequer amplified.",
			"Jimmy and Zack, the police explained, were last seen diving into a field of buttered quahogs.",
			"Typography is known for two-dimensional architecture and requires extra zeal within every job.",
			"William said that everything about his jacket was in quite good condition except for the zipper.",
			"The vegetarian menu included gazpacho, piquant julienne beets, rusk rounds with yogurt, and excellent flan.",
			"Jelly-like above the high wire, six quaking pachyderms kept the climax of the extravaganza in a dazzling state of flux.",
			"No kidding, Lorenzo called off his trip to visit Mexico City just because they told him the conquistadores were extinct.",
			"Forsaking monastic tradition, twelve jovial friars gave up their vocation for a questionable existence on the flying trapeze.",
			"An inspired calligrapher can create pages of beauty using stick ink, quill, brush, pick-axe, buzz saw, or even strawberry jam."
	};

	public static String[] GERMAN = {
			"Zwei Boxkämpfer jagen Eva quer durch Sylt.",
			"Mylord Schwejk quizt Express ab Ravigsfen.",
			"Franz jagt im komplett verwahrlosten Taxi quer durch Bayern.",
			"Typographie ist zweidimensionale Architektur und bedingt extra Qualität in jeder vollkommenen Ausfuehrung."
	};

	public static String[] SPAIN = {
			"Quiere la boca exhausta vid, kiwi, piña y fugaz jamón.",
			"Fabio me exige, sin tapujos, que añada cerveza al whisky.",
			"El veloz murciélago hindú comía feliz cardillo y kiwi. La cigüeña tocaba el saxofón detrás del palenque de paja."
	};

	public static String[] DUTCH = {
			"Sexy qua lijf, doch bang voor ’t zwempak.",
			"M’n chique juf zwiert langs de vip-skybox.",
			"De lompe gifbak choqueert zijn sexy vrouw.",
			"Filmquiz bracht knappe ex-yogi van de wijs.",
			"De quizmaster gaf zijn bleke ex-vrouw chips.",
			"Qua type blijft m’n ex-vrouw de logische keuze.",
			"Bas wil zelf gympjes kopen van de extra cheque.",
			"Pa’s wijze lynx bezag vroom het fikse aquaduct.",
			"Zweedse ex-VIP, behoorlijk gek op quantumfysica.",
			"Ex-quizmaster verkwanselde copyrightbriefjes.",
			"Qua sex is de ex van mijn zwager beter typt de chef koel.",
			"Quasi xenofobisch zag de verwijtende pater een lome yank.",
			"Ex-zakenvrouw geeft bijna acht smalle qwerty keyboards op."
	};

	public static String[] FRENCH = {
			"Portez ce vieux whisky au juge blond qui fume.",
			"Moi, je veux quinze clubs à golf et du whisky pur."
	};

	public static String[] CH = {
			"Příliš žluťoučký kůň úpěl ďábelské ódy!"
	};
}
